version: "3.11"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.11-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=teste
            - RABBITMQ_DEFAULT_PASS=teste123
        ports:
            - '5672:5672'
            - '15672:15672'