version: "3.11"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3.11-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=adm123
            - RABBITMQ_DEFAULT_VHOST=PriceBot
        ports:
            - '5672:5672'
            - '15672:15672'